using System.Buffers.Binary;
using System.Text;
using static HDRFixer.Core.ColorProfile.IccBinaryHelpers;
using static HDRFixer.Core.ColorProfile.IccConstants;

namespace HDRFixer.Core.ColorProfile;

public static class Mhc2ProfileWriter
{
    private static byte[] BuildMhc2Tag(double minNits, double maxNits, double[,] matrix3x4, double[,] regammaLut)
    {
        int lutSize = regammaLut.GetLength(1);
        using var ms = new MemoryStream();
        using var w = new BinaryWriter(ms);

        WriteTag(w, Tag_MHC2);
        WriteBE32(w, 0); // Reserved
        WriteBE32(w, lutSize);
        WriteBE32(w, ToS15F16(minNits));
        WriteBE32(w, ToS15F16(maxNits));

        int matrixOffset = Mhc2_MatrixOffset;
        int lut1Offset = 0; // Identity/Bypassed
        int lut2Offset = matrixOffset + Mhc2_MatrixSize;

        WriteBE32(w, matrixOffset);
        WriteBE32(w, lut1Offset);
        WriteBE32(w, lut2Offset);

        for (int r = 0; r < 3; r++)
            for (int c = 0; c < 4; c++)
                WriteBE32(w, ToS15F16(matrix3x4[r, c]));

        for (int ch = 0; ch < 3; ch++)
        {
            WriteTag(w, Tag_sf32);
            WriteBE32(w, 0); // Reserved
            for (int i = 0; i < lutSize; i++)
                WriteBE32(w, ToS15F16(regammaLut[ch, i]));
        }
        return ms.ToArray();
    }

    public static byte[] CreateProfile(string description, double maxNits, double minNits, double[,] matrix3x4, double[,] regammaLut)
    {
        var rXYZ = BuildXyzTag(Rec709_Red_X, Rec709_Red_Y, Rec709_Red_Z);
        var gXYZ = BuildXyzTag(Rec709_Green_X, Rec709_Green_Y, Rec709_Green_Z);
        var bXYZ = BuildXyzTag(Rec709_Blue_X, Rec709_Blue_Y, Rec709_Blue_Z);
        var wtpt = BuildXyzTag(D65_X, D65_Y, D65_Z);
        var lumi = BuildXyzTag(0, maxNits, 0);
        var trc = BuildCurvTag(Gamma_sRGB);
        var desc = BuildMlucTag(description);
        var cprt = BuildMlucTag("Generated by HDRFixer");
        var mhc2 = BuildMhc2Tag(minNits, maxNits, matrix3x4, regammaLut);

        var tags = new (uint sig, byte[] data, bool shared)[] {
            (Sig_desc, desc, false), (Sig_cprt, cprt, false),
            (Sig_rXYZ, rXYZ, false), (Sig_gXYZ, gXYZ, false), (Sig_bXYZ, bXYZ, false),
            (Sig_wtpt, wtpt, false), (Sig_lumi, lumi, false),
            (Sig_rTRC, trc, false), (Sig_gTRC, trc, true), (Sig_bTRC, trc, true),
            (Sig_MHC2, mhc2, false),
        };

        int headerSize = HeaderSize;
        int tagTableSize = 4 + tags.Length * 12;
        int dataOffset = headerSize + tagTableSize;
        if (dataOffset % 4 != 0) dataOffset += 4 - (dataOffset % 4);

        var tagOffsets = new int[tags.Length];
        var tagSizes = new int[tags.Length];
        int currentOffset = dataOffset;
        int trcOffset = -1;

        for (int i = 0; i < tags.Length; i++)
        {
            tagSizes[i] = tags[i].data.Length;
            if (tags[i].shared) { tagOffsets[i] = trcOffset; continue; }
            tagOffsets[i] = currentOffset;
            if (tags[i].sig == Sig_rTRC) trcOffset = currentOffset;
            currentOffset += tags[i].data.Length;
            if (currentOffset % 4 != 0) currentOffset += 4 - (currentOffset % 4);
        }

        int profileSize = currentOffset;
        using var ms = new MemoryStream();
        using var w = new BinaryWriter(ms);

        WriteBE32(w, profileSize); WriteBE32(w, 0); WriteBE32(w, Version4_4);
        WriteBE32(w, Class_Monitor); WriteBE32(w, Space_RGB); WriteBE32(w, PCS_XYZ);
        WriteBE16(w, 2026); WriteBE16(w, 2); WriteBE16(w, 18);
        WriteBE16(w, 0); WriteBE16(w, 0); WriteBE16(w, 0);
        WriteBE32(w, FileSignature); WriteBE32(w, Platform_Microsoft);
        WriteBE32(w, 0); WriteBE32(w, 0); WriteBE32(w, 0);
        WriteBE32(w, 0); WriteBE32(w, 0); WriteBE32(w, 0); WriteBE32(w, 0); WriteBE32(w, 0);
        WriteBE32(w, ToS15F16(D50_X)); WriteBE32(w, ToS15F16(D50_Y)); WriteBE32(w, ToS15F16(D50_Z));
        WriteBE32(w, 0);
        for (int i = 0; i < 16; i++) w.Write((byte)0);
        for (int i = 0; i < 20; i++) w.Write((byte)0);

        WriteBE32(w, tags.Length);
        for (int i = 0; i < tags.Length; i++)
        { WriteBE32(w, tags[i].sig); WriteBE32(w, tagOffsets[i]); WriteBE32(w, tagSizes[i]); }

        while (ms.Length < dataOffset) w.Write((byte)0);
        for (int i = 0; i < tags.Length; i++)
        {
            if (tags[i].shared) continue;
            while (ms.Length < tagOffsets[i]) w.Write((byte)0);
            w.Write(tags[i].data);
            while (ms.Length % 4 != 0) w.Write((byte)0);
        }
        while (ms.Length < profileSize) w.Write((byte)0);
        return ms.ToArray();
    }
}
